### ISSUE TITLE
Please create a fork of the Liftmaster plugin rather than creating a new one

### ISSUE THREAD

**Issue by AppleTechy** [rainlake/homebridge-platform-myq#7]
Liftmaster and Chamberlain both use the same servers. Liftmaster has gone through a lot more testing, and is most likely more stable. I appreciate the initiative you showed to create a new plugin but there are now 3 or 4 plugin that all do the same thing. It has become confusing to the user one which one they should download

**Comment by rainlake** [comment]
Lift master plugin does not do periodic check door state and does not support light switch. This project is well tested and also maintained regularly. It is your own choice to pick which one you use. Thanks for your advice though.

**Comment by AppleTechy** [comment]
That is what a fork it for adding your additions so they can be tested among many users. That is also how we can take the best parts of all the plugins to create 1 master plugin. If you wouldn't mind could you create a fork and add your chamberlain plugin modification to it.. Would love to add support for the lights. :)

**Comment by amitgandhinz** [comment]
I agree that it should be on one plugin - the liftmaster one.

**Comment by bobobox** [comment]
I'm not sure that I agree with the people telling @rainlake to re-do his work as a fork of the Liftmaster plugin. Frankly @rainlake's plugin already works better and has more features - and has a more sensible name too. It supports my lights and gets my garage door status correct, which the Liftmaster plugin never did (and a pull request to fix this has been sitting unresolved since February). 

It's not like a homebridge plugin like this contains such a vast amount of code that it's a huge waste to write another...

**Comment by amitgandhinz** [comment]
i don't disagree with the naming being more sensible here.  What i don't agree with is having two competing implementations when the community can instead work together on a common platform.  By having two, it reduces the pace of improvement on both implementations.

I think there does need to be a discussion of whether this one becomes the main implementation or the lift master one becomes the main one.  That discussion should happen in the open with the pro's and con's of each implementation and deciding together which one should be converged towards.

**Comment by AppleTechy** [comment]
Rainlake you on Slack? What your username?
